import os


class Config:
    AUTHORIZATION_API_HOST = os.getenv('AUTHORIZATION_API_HOST')
    AUTHORIZATION_API_PORT = int(os.getenv('AUTHORIZATION_API_PORT'))
    AUTHORIZATION_API_KEY = os.getenv('AUTHORIZATION_API_KEY')

    AUTHORIZATION_DATABASE_PASSWORD = os.getenv('AUTHORIZATION_DATABASE_PASSWORD')
    AUTHORIZATION_DATABASE_HOST = os.getenv('AUTHORIZATION_DATABASE_HOST')
    AUTHORIZATION_DATABASE_PORT = int(os.getenv('AUTHORIZATION_DATABASE_PORT'))
    AUTHORIZATION_DATABASE_NAME = os.getenv('AUTHORIZATION_DATABASE_NAME')

    AUTHORIZATION_DATABASE_URL = f'mysql+aiomysql://root:{AUTHORIZATION_DATABASE_PASSWORD}@{AUTHORIZATION_DATABASE_HOST:}:{AUTHORIZATION_DATABASE_PORT}/{AUTHORIZATION_DATABASE_NAME}'